"""
Garmin Agent Orchestrator - Plan & Code Execution

结构性编排器：把刚性两阶段流水线升级为"计划生成 → 代码执行/工具调用 → 结果解读"三层动态架构。

核心设计：
- 简单查询 → mode="tool" → 直接调用预设工具（保留快速路径）
- 复杂查询 → mode="code" → LLM 生成 Python 代码在受限沙箱中执行
- 闲聊    → mode="direct" → 直接回复

代码模式下，LLM 可以任意组合 client 的基础 API，自由处理数据，彻底解决"超级工具"不可扩展的问题。
"""

import io
import json
import logging
import contextlib
import traceback
from dataclasses import dataclass, field
from datetime import date
from typing import Literal, Optional, Dict, Any, List
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FutureTimeoutError

from langchain_core.messages import HumanMessage, SystemMessage

logger = logging.getLogger(__name__)


# ==========================================
# Plan Data Model
# ==========================================

@dataclass
class Plan:
    """Execution plan generated by the planner LLM."""
    mode: Literal["tool", "code", "direct"]
    tool_name: Optional[str] = None
    params: Optional[Dict[str, Any]] = None
    code: Optional[str] = None
    reasoning: str = ""
    reply: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "mode": self.mode,
            "tool_name": self.tool_name,
            "params": self.params,
            "code": self.code,
            "reasoning": self.reasoning,
            "reply": self.reply,
        }


# ==========================================
# Sandbox Executor
# ==========================================

class SandboxExecutor:
    """Restricted Python code execution environment for the agent.

    - Pre-injects `client` (GarminClient) and safe standard libraries
    - Restricts builtins to prevent dangerous operations
    - Captures stdout and the `result` variable
    - Enforces execution timeout
    """

    def __init__(self, client: Any, formatters_module: Any = None):
        self.client = client
        self.formatters = formatters_module

    def _get_safe_globals(self) -> Dict[str, Any]:
        """Build the restricted globals dict for code execution."""
        import collections
        import statistics
        import math
        import re
        import datetime

        safe_builtins = {
            "True": True,
            "False": False,
            "None": None,
            "len": len,
            "range": range,
            "enumerate": enumerate,
            "zip": zip,
            "map": map,
            "filter": filter,
            "sum": sum,
            "min": min,
            "max": max,
            "abs": abs,
            "round": round,
            "sorted": sorted,
            "list": list,
            "dict": dict,
            "tuple": tuple,
            "set": set,
            "str": str,
            "int": int,
            "float": float,
            "bool": bool,
            "print": print,
            "isinstance": isinstance,
            "hasattr": hasattr,
            "getattr": getattr,
            "setattr": setattr,
            "KeyError": KeyError,
            "ValueError": ValueError,
            "TypeError": TypeError,
            "AttributeError": AttributeError,
            "IndexError": IndexError,
            "Exception": Exception,
            "RuntimeError": RuntimeError,
        }

        globals_dict: Dict[str, Any] = {
            "__builtins__": safe_builtins,
            "client": self.client,
            "json": json,
            "datetime": datetime,
            "re": re,
            "math": math,
            "collections": collections,
            "statistics": statistics,
        }

        # Inject formatter helpers if available
        if self.formatters is not None:
            fmt = self.formatters
            for fname in [
                "format_distance", "format_duration", "format_pace",
                "format_pace_from_min_km", "format_heart_rate",
                "format_cadence", "format_date", "format_gct",
                "format_vo", "format_stride", "format_calories",
                "format_duration_minutes", "format_running_dynamics",
                "format_split_pace",
            ]:
                if hasattr(fmt, fname):
                    globals_dict[fname] = getattr(fmt, fname)

        return globals_dict

    def _run_code(self, code: str) -> Dict[str, Any]:
        """Actually run the code (runs in a separate thread for timeout control)."""
        stdout_capture = io.StringIO()
        locals_dict: Dict[str, Any] = {}

        with contextlib.redirect_stdout(stdout_capture):
            compiled = compile(code, "<agent_sandbox>", "exec")
            exec(compiled, self._get_safe_globals(), locals_dict)

        return {
            "stdout": stdout_capture.getvalue(),
            "result": locals_dict.get("result"),
            "locals": {k: v for k, v in locals_dict.items() if not k.startswith("_")},
        }

    def execute(self, code: str, timeout: int = 30) -> Dict[str, Any]:
        """Execute code with timeout and error isolation.

        Returns:
            Dict with keys: stdout, result, error, locals
        """
        with ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(self._run_code, code)
            try:
                result = future.result(timeout=timeout)
                result["error"] = None
                return result
            except FutureTimeoutError:
                return {
                    "stdout": "",
                    "result": None,
                    "error": f"代码执行超时（>{timeout}秒）。可能是循环未终止或 API 调用过多。",
                    "locals": {},
                }
            except Exception as e:
                return {
                    "stdout": "",
                    "result": None,
                    "error": f"{type(e).__name__}: {e}\n{traceback.format_exc()}",
                    "locals": {},
                }


# ==========================================
# Prompts
# ==========================================

def build_plan_prompt(today: str) -> str:
    """Build the planning prompt with today's date and all available APIs."""
    return f"""你是 Garmin 训练助手的计划生成模块。根据用户消息，分析需要什么数据、怎么拿到，然后输出执行计划。

## 核心决策逻辑

**Step 1: 判断查询复杂度**

- **简单查询**（可以用单个预设工具直接回答）→ mode="tool"
  例如："最近跑了什么"、"今天状态如何"、"体能水平"、"睡眠怎么样"

- **复杂查询**（需要多步组合、条件筛选、跨活动聚合、提取特定字段）→ mode="code"
  例如："配速>8:00的圈"、"本月步频<160的圈"、"最近5次长距离跑的平均心率趋势"、"找出所有掉速的圈"

- **闲聊/无关** → mode="direct"

**Step 2: 选择模式**

### mode="tool"（简单查询）

直接从下面的预设工具中选择一个：

| 工具 | 用途 | 参数 |
|------|------|------|
| get_latest_activity | 最近一次活动 | 无 |
| get_week_summary | 最近N周统计 | weeks(默认1) |
| get_daily_health_summary | 今日健康(睡眠+HRV+训练准备度) | date_str(默认今天) |
| get_training_capacity | 训练能力(VO2Max+比赛预测+乳酸阈值) | 无 |
| search_by_training_type | 按类型搜索 | training_type, limit(默认5) |
| search_activities | 关键词搜索 | keywords, start_date, end_date, limit |
| get_activity_detail | 活动详情(配速/步态/训练效果) | activity_id(不填=最近) |
| get_activity_splits | 分段配速 | activity_id |
| get_activity_hr_zones | 心率区间分布 | activity_id |
| classify_activity_type | 训练类型分析 | activity_id(不填=最近) |
| compare_interval_trainings | 间歇训练横向对比趋势 | limit(默认5) |
| evaluate_lap_quality | 圈质量评分(最佳/最差圈) | activity_id(不填=最近) |
| get_hr_zone_distribution | 心率区间详细分布(Z1-Z5) | activity_id(不填=最近) |
| filter_laps_by_pace | 按配速过滤圈(心率/步频/步幅/垂振) | pace_threshold, direction, activity_type, start_date, end_date |
| get_heart_rate_data | 心率数据 | date_str(默认今天) |
| get_resting_heart_rate | 静息心率 | date_str(默认今天) |
| get_sleep_data | 睡眠数据 | date_str(默认今天) |
| get_hrv_data | HRV数据 | date_str(默认今天) |
| get_training_status | 训练状态 | 无 |

### mode="code"（复杂查询）

当问题需要以下能力时，必须用 code 模式：
- 跨多个活动获取数据再筛选/聚合
- 按自定义条件过滤（如配速>8:00、步频<160、心率>170 等组合条件）
- 需要计算统计值（平均值、趋势、标准差等）
- 需要提取特定字段并重新组织数据结构

**代码编写规则：**
1. 代码必须是完整的、可独立执行的 Python 脚本
2. 使用 `client.xxx()` 直接调用 Garmin API 获取原始数据（返回 dict/list）
3. 不要使用预设工具函数（它们返回格式化字符串，不适合代码处理）
4. 可用辅助函数：`format_pace`, `format_distance`, `format_duration`, `format_heart_rate`, `format_cadence`, `format_date`, `format_gct`, `format_vo`, `format_stride`, `format_pace_from_min_km`
5. 可用标准库：`json`, `datetime`, `re`, `math`, `collections`, `statistics`
6. **必须把最终结果存入 `result` 变量**（dict/list/str 都可以）
7. 可以用 `print()` 输出中间过程信息
8. 注意错误处理：API 可能返回 None 或空列表
9. 日期格式使用 YYYY-MM-DD
10. 配速计算：speed (m/s) → pace_min_km = 1000 / (speed * 60)
11. 今天是 {today}

**需求扩展原则（重要！）：**
用户的查询往往只说了核心条件，你要主动扩展，让 result 包含完整上下文：

- 用户说「找配速>8的圈」→ result 应包含：每个活动的整体信息（日期/距离/均配速/均心率）+ 该活动中符合条件的圈（逐圈明细）+ 其余圈的汇总（数量/均配速）+ 全局汇总
- 用户说「最近5次间歇跑的均速」→ result 应包含：每次活动的基本信息 + 每次活动的每个 ACTIVE 段明细 + 各活动间的趋势对比
- 用户说「心率>160的圈」→ result 应包含：每个活动的概况 + 超阈值圈的明细（圈号/心率/配速）+ 其余圈汇总

代码结构建议：result = {{'threshold': '...', 'activities': [{{...activity_overview, 'target_laps': [...], 'other_laps_summary': {{...}}}}], 'global_summary': {{...}}}}

**可用的 client API：**
- `client.get_activities(limit=10, start=0)` → 最近活动列表
- `client.get_activities_by_date(start_date, end_date, activity_type="running")` → 按日期范围搜索
- `client.get_activity(activity_id)` → 单个活动详情
- `client.get_activity_splits(activity_id)` → 分圈数据（含 lapDTOs）
- `client.get_activity_split_summaries(activity_id)` → 分段摘要
- `client.get_activity_typed_splits(activity_id)` → 间歇训练的 ACTIVE/RECOVERY 分段
- `client.get_activity_hr_in_timezones(activity_id)` → 心率区间分布
- `client.get_activity_details(activity_id)` → 逐秒详细数据
- `client.get_activity_weather(activity_id)` → 活动天气
- `client.get_activity_power_in_timezones(activity_id)` → 功率区间
- `client.get_activity_exercise_sets(activity_id)` → 力量训练组数
- `client.get_activities_fordate(date_str)` → 某天的所有活动
- `client.get_heart_rates(date_str)` → 全天心率
- `client.get_rhr_day(date_str)` → 静息心率
- `client.get_hrv_data(date_str)` → HRV 数据
- `client.get_sleep_data(date_str)` → 睡眠数据
- `client.get_training_status(date_str)` → 训练状态
- `client.get_training_readiness(date_str)` → 训练准备度
- `client.get_fitnessage_data()` → 健身年龄 + VO2Max
- `client.get_race_predictions()` → 比赛预测
- `client.get_endurance_score()` → 耐力评分
- `client.get_hill_score(activity_id)` → 爬坡评分
- `client.get_lactate_threshold()` → 乳酸阈值
- `client.get_latest_activity()` → 最近一次活动（dict）
- `client.get_todays_activities()` → 今天的活动
- `client.get_week_activities(weeks=1)` → 最近几周活动

**活动对象常见字段：**
- `activityId`: 活动ID
- `activityName`: 活动名称
- `startTimeLocal`: 本地开始时间 "2026-05-09 06:30:00"
- `distance`: 距离（米）
- `duration`: 时长（秒）
- `averageSpeed`: 平均速度（m/s）
- `averageHR`: 平均心率
- `activityType.typeKey`: 类型如 "running", "hiking", "trail_running"

**分圈对象常见字段（lapDTOs 中的元素）：**
- `distance`: 圈距离（米）
- `averageSpeed`: 平均速度（m/s）
- `averageHR`: 平均心率
- `averageRunCadence`: 步频
- `strideLength`: 步幅（厘米）
- `verticalOscillation`: 垂直振幅（毫米）
- `groundContactTime`: 触地时间（毫秒）
- `duration`: 圈时长（秒）

### mode="direct"（闲聊）
直接生成友好回复，不调用任何工具。

## 输出格式

只输出 JSON，不要输出任何其他内容：

**tool 模式：**
```json
{{"mode":"tool","tool_name":"工具名","params":{{...}},"reasoning":"简要说明为什么选这个工具"}}
```

**code 模式：**
```json
{{"mode":"code","code":"完整的 Python 代码字符串","reasoning":"简要说明为什么需要写代码"}}
```

**direct 模式：**
```json
{{"mode":"direct","reply":"友好回复","reasoning":"简要说明"}}
```

## 示例

用户："最近跑了什么" → {{"mode":"tool","tool_name":"get_latest_activity","params":{{}},"reasoning":"简单查询，直接获取最近一次活动"}}

用户："今天状态如何" → {{"mode":"tool","tool_name":"get_daily_health_summary","params":{{}},"reasoning":"简单查询，直接获取今日健康摘要"}}

用户："这个月跑步或者徒步配速大于8分钟的圈的具体信息，心率、配速、步频、步幅、垂直振幅" → 
{{"mode":"code","code":"from datetime import date\\ntoday = date.today()\\nstart = today.replace(day=1).strftime('%Y-%m-%d')\\nend = today.strftime('%Y-%m-%d')\\nrunning = client.get_activities_by_date(start, end, 'running') or []\\nhiking = client.get_activities_by_date(start, end, 'hiking') or []\\nactivities = running + hiking\\n\\nthreshold = 8.0\\nresult = {{'threshold': f'>{{threshold}}min/km', 'activities': [], 'summary': {{'total_slow_laps': 0, 'total_activities_with_slow': 0}}}}\\n\\nfor a in activities:\\n    aid = a.get('activityId')\\n    a_name = a.get('activityName', '未命名')\\n    a_date = (a.get('startTimeLocal') or '')[:10]\\n    a_type = (a.get('activityType') or {{}}).get('typeKey', '')\\n    a_speed = a.get('averageSpeed') or 0\\n    a_pace = format_pace_from_min_km(1000/(a_speed*60)) if a_speed > 0 else 'N/A'\\n    a_hr = a.get('averageHR')\\n    a_dist = round((a.get('distance') or 0)/1000, 2)\\n\\n    splits = client.get_activity_splits(aid)\\n    laps = splits.get('lapDTOs', []) if splits else []\\n    if not laps: continue\\n\\n    slow_laps = []\\n    fast_laps = []\\n    for i, lap in enumerate(laps, 1):\\n        speed = lap.get('averageSpeed') or 0\\n        if speed <= 0: continue\\n        pace_min = 1000 / (speed * 60)\\n        lap_info = {{'lap': i, 'pace': format_pace_from_min_km(pace_min), 'pace_min': round(pace_min,2), 'hr': lap.get('averageHR'), 'cadence': lap.get('averageRunCadence'), 'stride_cm': lap.get('strideLength'), 'vo_mm': lap.get('verticalOscillation'), 'dist_m': round(lap.get('distance',0))}}\\n        if pace_min > threshold:\\n            slow_laps.append(lap_info)\\n        else:\\n            fast_laps.append(lap_info)\\n\\n    act_entry = {{'activity_id': aid, 'name': a_name, 'date': a_date, 'type': a_type, 'distance_km': a_dist, 'avg_pace': a_pace, 'avg_hr': a_hr, 'total_laps': len(laps), 'slow_laps': slow_laps, 'fast_laps_count': len(fast_laps), 'fast_laps_avg_pace': format_pace_from_min_km(sum(l['pace_min'] for l in [{{\"pace_min\": 1000/(lap.get('averageSpeed',1)*60)}} for lap in laps if (lap.get('averageSpeed') or 0)>0 and 1000/(lap.get('averageSpeed',1)*60)<=threshold])/max(1,len([lap for lap in laps if (lap.get('averageSpeed') or 0)>0 and 1000/(lap.get('averageSpeed',1)*60)<=threshold]))) if any((lap.get('averageSpeed') or 0)>0 and 1000/(lap.get('averageSpeed',1)*60)<=threshold for lap in laps) else 'N/A'}}\\n    result['activities'].append(act_entry)\\n    result['summary']['total_slow_laps'] += len(slow_laps)\\n    if slow_laps: result['summary']['total_activities_with_slow'] += 1\\n\\nresult['activities'].sort(key=lambda x: x['date'])\\nprint(f\"共分析 {{len(result['activities'])}} 次活动，找到 {{result['summary']['total_slow_laps']}} 个慢圈\")","reasoning":"需要跨活动搜索、获取分圈、按配速筛选，同时保留每个活动的全貌（整体均速/心率）和其他圈的汇总，以便对比分析，属于复杂查询，必须写代码"}}

用户："hello" → {{"mode":"direct","reply":"嘿！我是你的 Garmin 训练教练 🏃 直接问我关于跑步、训练、健康的问题就行！","reasoning":"闲聊"}}

## 注意
- 只输出 JSON
- code 模式的代码必须是单行字符串（用 \\n 换行），或标准 JSON 字符串转义
- 日期、范围、数量都从用户的话里推断，不要留空
- 今天是 {today}
"""


SYNTHESIS_PROMPT = """你是 Garmin 训练助手，一个专业、主动的跑步教练。

## 数据来源标注（必须遵守！）

在回复开头标注数据来源：
- 如果数据来自 Garmin 真实 API → 在标题后加 "📡 数据来自 Garmin"
- 如果数据是模拟/缓存 → 加 "📦 数据来自缓存"
- 如果执行出错 → 加 "⚠️ 数据获取出现问题"

## 核心原则：明细优先，总结其次

**你的首要职责是忠实呈现数据明细，不允许用总结替代明细。**

判断规则：
- 执行结果包含「列表、分圈、多条记录」→ 必须逐条/逐圈输出，再做汇总
- 执行结果是「单个活动的摘要数据」→ 可以用关键数据格式
- 执行结果是「健康/状态类数据」→ 可以用关键数据格式

## 数据明细的输出规范

当结果包含多条记录（分圈、多活动、趋势数据）时，必须：

### 1. 按活动分组展示

对每一个活动，先输出活动头部信息，再输出该活动的圈数明细：

```
📅 [日期] [活动名] | [ID:xxxxx]
   总览：距离 X.Xkm | 均配速 X:XX/km | 均心率 XXXbpm

   ⚠️ 慢圈（配速 > 阈值）：
   | 圈号 | 配速 | 心率 | 步频 | 步幅 | 垂振 |
   |------|------|------|------|------|------|
   | 圈3  | 8:23 | 158  | 162  | 98cm | 8.2  |

   ✅ 其他圈概况：共X圈，均配速X:XX，均心率XXX
```

### 2. 汇总放在最后

所有活动展示完之后，再输出整体汇总：
- 共涉及几次活动，总共几个慢圈
- 哪次活动慢圈最多
- 整体慢圈的平均心率/配速

## 回复风格

- 🔥 **主动**：直接给结论和建议，不要问用户"你想了解什么"
- 🏃 **专业**：用教练语气，专业但亲切
- 📏 **精确**：距离 km，配速 分:秒/km，心率 bpm
- 💡 **有用**：每次回复必须包含具体的下一步建议
- 📊 **数据驱动**：必须基于工具返回的真实数据，禁止编造任何数值

## 格式选择

**情况A：结果含多条明细记录（分圈/多活动）** → 用「按活动分组 + 明细表格 + 末尾汇总」格式（见上方规范）

**情况B：结果是单个活动或健康摘要** → 用以下格式：

📊 **[标题]** 📡 数据来自 Garmin

[1-2句话直接给结论]

📌 关键数据：
• 数据项：数值

💡 建议：[1-3条具体可执行的建议]

🔥 你可以试试：[主动推荐1-2个相关的后续查询]

## 绝对禁止
- ❌ 不要问用户"你想了解什么"、"需要我帮你查什么"
- ❌ 不要问用户要 activity_id，自己去查
- ❌ **不要编造数据**：如果数据缺失或执行出错，如实说明，不要填充假数据
- ❌ 不要说"如果您有其他问题"之类的客套话
- ❌ **不要删除活动 ID**：工具返回的 [ID:xxxxx] 必须保留在回复中
- ❌ **绝对禁止用总结替代明细**：结果有几条记录就输出几条，不允许说"共有X个慢圈，平均配速Y"来代替逐圈列表

## 错误处理

如果工具执行返回了错误信息，请：
1. 如实告诉用户获取数据时遇到了问题
2. 简要解释可能的原因
3. 给出可以尝试的替代查询
"""


# ==========================================
# Planner
# ==========================================

class Planner:
    """Generates execution plans using an LLM."""

    def __init__(self, llm: Any):
        self.llm = llm

    def create_plan(self, user_message: str, history_messages: Optional[List[Any]] = None) -> Plan:
        """Generate a Plan from the user message."""
        import re as _re
        today = date.today().strftime("%Y-%m-%d")
        system_content = build_plan_prompt(today)

        messages = [SystemMessage(content=system_content)]
        if history_messages:
            for msg in history_messages[-6:]:  # 从4条扩展到6条
                content = msg.content if hasattr(msg, "content") else str(msg)
                if len(content) > 800:
                    # 先提取 ID，截断后补回，确保上下文引用不丢失
                    ids_found = _re.findall(r'\[ID:\d+\]', content)
                    content = content[:700]
                    if ids_found:
                        content += "... [涉及活动: " + " ".join(ids_found) + "]"
                    else:
                        content += "..."
                if isinstance(msg, HumanMessage):
                    messages.append(HumanMessage(content=content))
                else:
                    from langchain_core.messages import AIMessage
                    if isinstance(msg, AIMessage):
                        messages.append(AIMessage(content=content))
        messages.append(HumanMessage(content=user_message))

        try:
            response = self.llm.invoke(messages)
            raw = response.content

            if isinstance(raw, list):
                texts = [item.get("text", "") for item in raw if isinstance(item, dict) and item.get("type") == "text"]
                content = "".join(texts)
            else:
                content = str(raw)

            # Extract JSON
            import re as _re
            json_match = _re.search(r'```(?:json)?\s*(\{.*?\})\s*```', content, _re.DOTALL)
            if json_match:
                content = json_match.group(1)

            plan_dict = json.loads(content.strip())
            logger.info(f"Plan: {plan_dict}")

            return Plan(
                mode=plan_dict.get("mode", "tool"),
                tool_name=plan_dict.get("tool_name"),
                params=plan_dict.get("params"),
                code=plan_dict.get("code"),
                reasoning=plan_dict.get("reasoning", ""),
                reply=plan_dict.get("reply"),
            )
        except Exception as e:
            logger.warning(f"Plan generation failed: {e}")
            # Fallback to get_latest_activity
            return Plan(
                mode="tool",
                tool_name="get_latest_activity",
                params={},
                reasoning=f"计划生成失败，fallback: {e}",
            )
